# Generated by Django 3.0.4 on 2020-04-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagem',
            new_name='image',
        ),
    ]
